apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <yourname>-wordpress              
spec:
  ingressClassName: kommander-traefik
  rules:
    - host: <yourname>-wordpress.arief.com       
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <yourname>-wordpress  
                port:
                  number: 80
